print ("My Name is Mutee and this is my Assignment of PIAIC Lecture 2")
print ("In this Assignment I have learned to perform Arithmetic Operations")
a=input ("Enter 1st  Number")
b=input ("Enter 2nd  Number")
print ("Division=") 
print (int(a)/int(b))
print ("Multiplication=") 
print (int(a)*int(b))
print ("Addition=") 
print (int(a)+int(b))
print ("Subtraction=") 
print (int(a)-int(b))
print ("Thanks!")